# Generated by Django 2.2.3 on 2019-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190727_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False),
        ),
    ]
